# syntax=docker/dockerfile:1
FROM node
FROM continuumio/miniconda3

# Set web application environment variables
ENV FLASK_PORT=8000
ENV PRODUCTION=false
ENV BACKEND_DOMAIN=http://localhost:8000
ENV TRAME_DOMAIN=http://localhost:8080

# # Install wget
RUN apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN conda create -n pv-env python=3.12 \
    && conda install -n pv-env -c conda-forge libgomp numpy flask festim python-gmsh gmsh python-dotenv \
    && conda clean -afy


# Expose Flask backend port
EXPOSE 8000

WORKDIR /festim-view

COPY . .

# Expose Next.js application port
EXPOSE 3000
RUN apt-get update && apt-get install -y npm
RUN npm i --omit=dev \ && npm i concurrently

CMD ["npm", "run", "start:without_trame"]