FROM kitware/trame:uv

ENV TRAME_PYTHON=3.12
ENV TRAME_CLIENT_TYPE=vue3

# RUN install -d -o trame-user -g trame-user /deploy
# Install ParaView (with ADIOS2 support)
ARG PV_URL=https://www.paraview.org/files/v6.1/ParaView-6.1.1-MPI-Linux-Python3.12-x86_64.tar.gz
RUN mkdir -p /opt/paraview && cd /opt/paraview && wget -qO- $PV_URL | tar --strip-components=1 -xzv
ENV TRAME_PARAVIEW=/opt/paraview
# ENV VTK_DEFAULT_OPENGL_WINDOW=vtkEGLRenderWindow

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpciaccess0 \
    libgl1 \
    libegl1 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    libxkbcommon-x11-0 \
    libdbus-1-3 \
 && rm -rf /var/lib/apt/lists/*


COPY --chown=trame-user:trame-user ./trame /deploy

RUN /opt/trame/entrypoint.sh build \
    && $TRAME_VENV/bin/python -c "import wslink"

